common: &default_settings
  send_to: 'tatum@ashlandstudios.com'
  send_as: 'do_not_reply@phoebeboothantiques.com'
  domain: 'phoebeboothantiques.com'
  user_name: 'admin@phoebeboothantiques.com'
  password: 'pa88word'


development:
  <<: *default_settings
test:
  <<: *default_settings
staging:
  <<: *default_settings

production:
  send_to: 'phoebe@phoebeboothantiques.com'
  send_as: 'do_no_reply@phoebeboothantiques.com'
  domain: 'phoebeboothantiques.com'
  user_name: 'admin@phoebeboothantiques.com'
  password: 'pa88word'
