development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO

staging:
  solr:
    hostname: ashlandstudios.com
    path: '/solr/antiques-staging.herokuapp.com'
    port: 8080
    log_level: INFO

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
